version: "2"
linters:
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - errorlint
    - funlen
    - goconst
    - gosec
    - importas
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - whitespace
  settings:
    funlen:
      lines: 150
      statements: 70
      ignore-comments: true
    gocognit:
      min-complexity: 20
    godox:
      keywords:
        - TODO
        - BUG
        - FIXME
        - NOTE
        - OPTIMIZE
        - HACK
    govet:
      enable:
        - shadow
    misspell:
      mode: restricted
      locale: US
      ignore-rules:
        - Lustre
    unparam:
      check-exported: true
    whitespace:
      multi-if: true
      multi-func: true
    dupl:
      threshold: 200
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - funlen
          - gocyclo
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$