kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:

  - role: control-plane
    labels:
      nodeGroup: system

  - role: worker
    labels:
      nodeGroup: worker


  - role: worker
    labels:
      nodeGroup: worker
