apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "node-role-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "node-role-controller.labels" . | nindent 4 }}
