apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-role-controller
  namespace: node-labeler
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: node-role-controller
          image: ghcr.io/mchmarny/node-role-controller:v0.3.1@sha256:7f69b11335087e90732b3ba40f3e3cbd6219be69899f39ad83c7bf5b91ffff33
