apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-role-controller
  namespace: node-labeler
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: node-role-controller
          image: ghcr.io/mchmarny/node-role-controller:v0.3.3@sha256:11adb28b55d4c7af0e3719dfcda557922caab0ad44cc8b729e785d851bc306c4
