apiVersion: v1
kind: ConfigMap
metadata:
  name: node-role-controller-config
  namespace: node-labeler
data:
  roleLabel: "nodeGroup"  # value of this label will be the node role
  roleReplace: "true"  # whether to replace the existing node role if one exists
  logLevel: "debug"  # logging level for the controller
