name: lock_threads

on:
  schedule:
    - cron: '0 7 * * *'  # daily at 07:00 UTC
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:

  lock:
    name: Lock closed issues and PRs
    runs-on: ubuntu-latest
    if: github.repository == 'mchmarny/rolesetter'
    timeout-minutes: 10
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: dessant/lock-threads@1bf7753dd3b9a6065b5f64d3b9dcf48b3a59cd1d  # v5.0.1
        with:
          issue-inactive-days: '90'
          pr-inactive-days: '90'
          issue-comment: |
            This issue has been automatically locked since it has been closed for 90 days
            with no further activity. Please open a new issue for related concerns.
          pr-comment: |
            This pull request has been automatically locked since it has been closed for 90 days
            with no further activity. Please open a new pull request for related changes.
          issue-lock-reason: 'resolved'
          pr-lock-reason: 'resolved'
