name: on_push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  versions:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      go: ${{ steps.v.outputs.go }}
      golangci_lint: ${{ steps.v.outputs.golangci_lint }}
      scan_severity: ${{ steps.v.outputs.scan_severity }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
    - name: Load versions
      id: v
      uses: ./.github/actions/load-versions

  helm-lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
    - uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4  # v4.3.1
    - run: helm lint chart/

  test:
    needs: [versions]
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      id-token: write
    steps:
    - uses: mchmarny/common/go-test@eba3b1848a7cacb533285a15b01509d020513f25  # main
      with:
        go-version: ${{ needs.versions.outputs.go }}
        scan-severity: ${{ needs.versions.outputs.scan_severity }}
        linter-version: ${{ needs.versions.outputs.golangci_lint }}
