name: test

on:
  workflow_call: {}

permissions:
  contents: read

jobs:

  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      id-token: write
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

    - name: Load versions
      id: versions
      uses: ./.github/actions/load-versions

    - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c  # v6.4.0
      with:
        go-version: ${{ steps.versions.outputs.go }}
        cache: true
        cache-dependency-path: go.sum

    - name: Tidy
      run: go mod tidy

    - name: Test
      run: |
        go test -count=1 -covermode=atomic -coverprofile=coverage.out ./...
        go tool cover -func=coverage.out

    - name: Coverage
      uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2  # v6.0.0
      with:
        fail_ci_if_error: true
        use_oidc: true

    - name: Lint Go
      uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20  # v9.2.0
      with:
        version: ${{ steps.versions.outputs.golangci_lint }}

    - name: Lint YAML
      uses: karancode/yamllint-github-action@4052d365f09b8d34eb552c363d1141fd60e2aeb2  # v3.0.0
      with:
        yamllint_config_filepath: .yamllint

    - name: Install Trivy
      run: |
        sudo apt-get install -y wget apt-transport-https gnupg
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install -y trivy
        trivy --version

    - name: Scan
      run: |
        trivy fs . \
          --ignore-unfixed \
          --format sarif \
          --output trivy-results.sarif \
          --severity ${{ steps.versions.outputs.scan_severity }} \
          --exit-code 1

    - name: Upload Scan Results
      if: always()
      uses: github/codeql-action/upload-sarif@c10b8064de6f491fea524254123dbe5e09572f13  # v4.35.1
      with:
        sarif_file: trivy-results.sarif
